/*
 * Copyright (c) 2001, 2002 The XDoclet team
 * All rights reserved.
 */
package xdoclet.modules.bea.wls.web;

/**
 * @author    Ara Abrahamian (ara_e_w@yahoo.com)
 * @created   May 31, 2002
 * @version   $Revision: 1.2 $
 */
public final class XDocletModulesBeaWlsWebMessages
{
    /**
     * @msg.bundle   msg="Generated by XDoclet. Use weblogicwebxml''s description attribute to modify this value."
     */
    public final static String GENERATED_ATTRIBUTE = "GENERATED_ATTRIBUTE";
}
