/*
 * Copyright (c) 2001, 2002 The XDoclet team
 * All rights reserved.
 */
package xdoclet.modules.exolab.castor.ejb;

/**
 * @author    <a href="mailto:stevensa@users.sourceforge.net">Andrew Stevens</a>
 * @created   August 15, 2002
 * @version   $Revision: 1.2 $
 */
public final class XDocletModulesCastorEjbMessages
{
    /**
     * @msg.bundle   msg="This mapping file is generated by XDoclet. Please do not edit!"
     */
    public final static String DO_NOT_EDIT = "DO_NOT_EDIT";

    /**
     * @msg.bundle   msg="Mapping for class {0}"
     */
    public final static String MAPPING_FOR = "MAPPING_FOR";

    /**
     * @msg.bundle   msg="Define your key-generator declaration in a file called key-generator.xml and place it in your
     *      merge directory."
     */
    public final static String MERGE_KEY_GENERATOR = "MERGE_KEY_GENERATOR";

}

