/*
 * Copyright (c) 2001, 2002 The XDoclet team
 * All rights reserved.
 */
package xdoclet.modules.apache.struts.ejb;

/**
 * @author    Ara Abrahamian (ara_e_w@yahoo.com)
 * @created   May 31, 2002
 * @version   $Revision: 1.4 $
 */
public final class XDocletModulesApacheStrutsEjbMessages
{
    /**
     * @msg.bundle   msg="''pattern'' parameter does not have a '''{1'}'' in it. '''{1'}'' is replaced by form name."
     */
    public final static String PATTERN_HAS_NO_FORM_PLACEHOLDER = "PATTERN_HAS_NO_FORM_PLACEHOLDER";

    /**
     * @msg.bundle   msg="Constructor that takes the data object as argument."
     */
    public final static String FORM_DATAOBJECT_CONSTRUCTOR = "FORM_DATAOBJECT_CONSTRUCTOR";

    /**
     * @msg.bundle   msg="Default empty constructor."
     */
    public final static String FORM_EMPTY_CONSTRUCTOR = "FORM_EMPTY_CONSTRUCTOR";

    /**
     * @msg.bundle   msg="Generated by XDoclet/ejbdoclet/strutsform. This class can be further processed with
     *      XDoclet/webdoclet/strutsconfigxml."
     */
    public final static String FORM_GENERATED = "FORM_GENERATED";

    /**
     * @msg.bundle   msg="--> {0}"
     */
    public final static String GENERATING_FILE = "GENERATING_FILE";

    /**
     * @msg.bundle   msg="Generating Struts Form classes for ''{0}''."
     */
    public final static String GENERATING_FORMS_FOR = "GENERATING_FORMS_FOR";

    /**
     * @msg.bundle   msg="Struts version ''{0}'' found, requires ''{1}'' for ''{2}''."
     */
    public final static String BAD_STRUTS_VERSION = "BAD_STRUTS_VERSION";
}
