/*
 * Copyright (c) 2001, 2002 The XDoclet team
 * All rights reserved.
 */
package xdoclet.modules.ejb;

/**
 * @author    Ara Abrahamian (ara_e_w@yahoo.com)
 * @created   May 31, 2002
 * @version   $Revision: 1.14 $
 */
public final class XDocletModulesEjbMessages
{
    /**
     * @msg.bundle   msg="Generated by XDoclet - Do not edit!"
     */
    public final static String DO_NOT_EDIT = "DO_NOT_EDIT";

    /**
     * @msg.bundle   msg="XDoclet can''t guess what CMP version to use for {0} because the <entitycmp> task isn't used,
     *      and there is no ejb:bean cmp-version tag. Please use one of them."
     */
    public final static String CANT_GUESS_CMP_VERSION = "CANT_GUESS_CMP_VERSION";

    /**
     * @msg.bundle   msg="Session layer for {0}."
     */
    public final static String SESSION_LAYER_FOR = "SESSION_LAYER_FOR";

    /**
     * @msg.bundle   msg="Home interface for {0}."
     */
    public final static String HOME_INTERFACE_FOR = "HOME_INTERFACE_FOR";

    /**
     * @msg.bundle   msg="Local home interface for {0}."
     */
    public final static String LOCAL_HOME_INTERFACE_FOR = "LOCAL_HOME_INTERFACE_FOR";

    /**
     * @msg.bundle   msg="Lookup using {0}"
     */
    public final static String UTIL_LOOKUP_USING = "UTIL_LOOKUP_USING";

    /**
     * @msg.bundle   msg="Local interface for {0}."
     */
    public final static String LOCAL_INTERFACE_FOR = "LOCAL_INTERFACE_FOR";

    /**
     * @msg.bundle   msg="Remote interface for {0}."
     */
    public final static String REMOTE_INTERFACE_FOR = "REMOTE_INTERFACE_FOR";

    /**
     * @msg.bundle   msg="Utility class for {0}."
     */
    public final static String UTILITY_CLASS_FOR = "UTILITY_CLASS_FOR";

    /**
     * @msg.bundle   msg="Data Access Object interface for {0}."
     */
    public final static String DAO_FOR = "DAO_FOR";

    /**
     * @msg.bundle   msg="DAO not defined in JNDI ''java:comp/env/{0}''"
     */
    public final static String DAO_IMPL_JNDI_NOT_SPECIFIED = "DAO_IMPL_JNDI_NOT_SPECIFIED";

    /**
     * @msg.bundle   msg="Exception while looking in JNDI for ''java:comp/env/{0}''"
     */
    public final static String DAO_JNDI_EXCEPTION = "DAO_JNDI_EXCEPTION";

    /**
     * @msg.bundle   msg="Primary key for {0}."
     */
    public final static String PRIMARY_KEY_FOR = "PRIMARY_KEY_FOR";

    /**
     * @msg.bundle   msg="CMP layer for {0}."
     */
    public final static String CMP_LAYER_FOR = "CMP_LAYER_FOR";

    /**
     * @msg.bundle   msg="Session facade for {0}."
     */
    public final static String SESSION_FACADE_FOR = "SESSION_FACADE_FOR";
    /**
     * @msg.bundle   msg="Remote facade for {0}."
     */
    public final static String REMOTE_FACADE_FOR = "REMOTE_FACADE_FOR";

    /**
     * @msg.bundle   msg="BMP layer for {0}."
     */
    public final static String BMP_LAYER_FOR = "BMP_LAYER_FOR";

    /**
     * @msg.bundle   msg="Data object for {0}."
     */
    public final static String DATA_OBJECT_FOR = "DATA_OBJECT_FOR";

    /**
     * @msg.bundle   msg="Value object for {0}."
     */
    public final static String VALUE_OBJECT_FOR = "VALUE_OBJECT_FOR";

    /**
     * @msg.bundle   msg="A Value Object has an identity if the attributes making its Primary Key have all been set. An
     *      object without identity is never equal to any other object."
     */
    public final static String VALUE_OBJECT_IDENTITY_COMMENT = "VALUE_OBJECT_IDENTITY_COMMENT";

    /**
     * @msg.bundle   msg="if this instance has an identity."
     */
    public final static String VALUE_OBJECT_IDENTITY_RETURN = "VALUE_OBJECT_IDENTITY_RETURN";

    /**
     * @msg.bundle   msg="Generating Util class for ''{0}''."
     */
    public final static String GENERATING_UTIL_FOR = "GENERATING_UTIL_FOR";

    /**
     * @msg.bundle   msg="Generating DAO class for ''{0}''."
     */
    public final static String GENERATING_DAO_FOR = "GENERATING_DAO_FOR";

    /**
     * @msg.bundle   msg="Generating Data Object class for ''{0}''."
     */
    public final static String GENERATING_DATAOBJECT_FOR = "GENERATING_DATAOBJECT_FOR";
    /**
     * @msg.bundle   msg="Generating Value Object class: ''{0}''."
     */
    public final static String GENERATING_VALUEOBJECT_FOR = "GENERATING_VALUEOBJECT_FOR";

    /**
     * @msg.bundle   msg="Generating EJB deployment descriptor ({0})."
     */
    public final static String GENERATING_DD = "GENERATING_DD";

    /**
     * @msg.bundle   msg="Generating BMP class for ''{0}''."
     */
    public final static String GENERATING_BMP_FOR = "GENERATING_BMP_FOR";

    /**
     * @msg.bundle   msg="Generating CMP class for ''{0}''."
     */
    public final static String GENERATING_CMP_FOR = "GENERATING_CMP_FOR";

    /**
     * @msg.bundle   msg="Generating PK class for ''{0}''."
     */
    public final static String GENERATING_PK_FOR = "GENERATING_PK_FOR";

    /**
     * @msg.bundle   msg="Generating Home interface for ''{0}''."
     */
    public final static String GENERATING_HOME_FOR = "GENERATING_HOME_FOR";

    /**
     * @msg.bundle   msg="Generating Local Home interface for ''{0}''."
     */
    public final static String GENERATING_LOCALHOME_FOR = "GENERATING_LOCALHOME_FOR";

    /**
     * @msg.bundle   msg="Generating Local interface for ''{0}''."
     */
    public final static String GENERATING_LOCAL_FOR = "GENERATING_LOCAL_FOR";

    /**
     * @msg.bundle   msg="Generating Remote interface for ''{0}''."
     */
    public final static String GENERATING_REMOTE_FOR = "GENERATING_REMOTE_FOR";

    /**
     * @msg.bundle   msg="Generating Session class for ''{0}''."
     */
    public final static String GENERATING_SESSION_FOR = "GENERATING_SESSION_FOR";

    /**
     * @msg.bundle   msg="Generating Facade EJB class for ''{0}''."
     */
    public final static String GENERATING_FACADE_FOR = "GENERATING_FACADE_FOR";

    /**
     * @msg.bundle   msg="Generating Remote Facade class for ''{0}''."
     */
    public final static String GENERATING_REMOTE_FACADE_FOR = "GENERATING_REMOTE_FACADE_FOR";

    /**
     * @msg.bundle   msg="Unsupported EJB Spec.: {0}"
     */
    public final static String UNSUPPORTED_EJB_SPEC = "UNSUPPORTED_EJB_SPEC";

    /**
     * @msg.bundle   msg="{0} has declared more than one ejb:relation. That''s illegal."
     */
    public final static String MULTIPLE_RELATIONS = "MULTIPLE_RELATIONS";

    /**
     * @msg.bundle   msg="must have attribute \"name\" for ejb:relation {0}"
     */
    public final static String RELATION_MUST_HAVE_NAME = "RELATION_MUST_HAVE_NAME";

    /**
     * @msg.bundle   msg="The {0} relation is declared in too many places. It''s declared in {1}, {2} and {3}."
     */
    public final static String RELATION_TOO_MANY_NAMES = "RELATION_TOO_MANY_NAMES";

    /**
     * @msg.bundle   msg="The relation with the name \"{0}\" declared in {1} seems to be unidirectional since it does
     *      not occur anywhere else. The target-ejb parameter must therefore be specified."
     */
    public final static String RELATION_NEEDS_TARGET = "RELATION_NEEDS_TARGET";

    /**
     * @msg.bundle   msg="The relation with the name \"{0}\" declared in {1} seems to be bidirectional since it is
     *      declared in two places. The target-ejb parameter must not be specified for bidirectional relationships."
     */
    public final static String RELATION_NEEDS_NO_TARGET = "RELATION_NEEDS_NO_TARGET";

    /**
     * @msg.bundle   msg="Should never swap for unidirectional relationships"
     */
    public final static String RELATION_SWAP_UNI = "RELATION_SWAP_UNI";

    /**
     * @msg.bundle   msg="Permission for findByPK method"
     */
    public final static String DD_FINDBYPK_PERM = "DD_FINDBYPK_PERM";

    /**
     * @msg.bundle   msg="description not supported yet by ejbdoclet"
     */
    public final static String DESCRIPTION_NOT_SUPPORTED = "DESCRIPTION_NOT_SUPPORTED";

    /**
     * @msg.bundle   msg="\"Wrong version. Had \" + getVersion() + \", got \" + dataHolder.getVersion()"
     */
    public final static String ENTITY_DATAHOLDER_VERSION = "ENTITY_DATAHOLDER_VERSION";

    /**
     * @msg.bundle   msg="Version number for soft locking"
     */
    public final static String SOFT_LOCK_VERSION = "SOFT_LOCK_VERSION";

    /**
     * @msg.bundle   msg="Cached remote home (EJBHome). Uses lazy loading to obtain its value (loaded by getHome()
     *      methods)."
     */
    public final static String UTIL_CACHED_REMOTE = "UTIL_CACHED_REMOTE";

    /**
     * @msg.bundle   msg="Cached local home (EJBLocalHome). Uses lazy loading to obtain its value (loaded by
     *      getLocalHome() methods)."
     */
    public final static String UTIL_CACHED_LOCAL = "UTIL_CACHED_LOCAL";

    /**
     * @msg.bundle   msg="Local homes shouldn''t be narrowed, as there is no RMI involved."
     */
    public final static String UTIL_LOCALHOME_NOT_NARROWED = "UTIL_LOCALHOME_NOT_NARROWED";

    /**
     * @msg.bundle   msg="Obtain local home interface from default initial context"
     */
    public final static String UTIL_OBTAIN_LOCALHOME_DEF_IC = "UTIL_OBTAIN_LOCALHOME_DEF_IC";

    /**
     * @msg.bundle   msg="Obtain remote home interface from parameterised initial context"
     */
    public final static String UTIL_OBTAIN_HOME_PARAM_IC = "UTIL_OBTAIN_HOME_PARAM_IC";

    /**
     * @msg.bundle   msg="Obtain remote home interface from default initial context"
     */
    public final static String UTIL_OBTAIN_HOME_DEF_IC = "UTIL_OBTAIN_HOME_DEF_IC";

    /**
     * @msg.bundle   msg="Parameters to use for creating initial context"
     */
    public final static String UTIL_IC_PARAMETERS = "UTIL_IC_PARAMETERS";

    /**
     * @msg.bundle   msg="Home interface lookup methods"
     */
    public final static String UTIL_HOME_LOOKUPS = "UTIL_HOME_LOOKUPS";

    /**
     * @msg.bundle   msg="Obtain initial context"
     */
    public final static String UTIL_OBTAIN_IC = "UTIL_OBTAIN_IC";

    /**
     * @msg.bundle   msg="A 32 byte GUID generator (Globally Unique ID). These artificial keys SHOULD <strong>NOT
     *      </strong> be seen by the user,"
     */
    public final static String UTIL_GUID_1 = "UTIL_GUID_1";

    /**
     * @msg.bundle   msg="not even touched by the DBA but with very rare exceptions, just manipulated by the database
     *      and the programs."
     */
    public final static String UTIL_GUID_2 = "UTIL_GUID_2";

    /**
     * @msg.bundle   msg="Usage: Add an id field (type java.lang.String) to your EJB, and add
     *      setId(XXXUtil.generateGUID(this)); to the ejbCreate method."
     */
    public final static String UTIL_GUID_USAGE = "UTIL_GUID_USAGE";

    /**
     * @msg.bundle   msg="Cached per JVM server IP."
     */
    public final static String UTIL_GUID_IP = "UTIL_GUID_IP";

    /**
     * @msg.bundle   msg="initialise the secure random instance"
     */
    public final static String UTIL_GUID_SECURERANDOM = "UTIL_GUID_SECURERANDOM";

    /**
     * @msg.bundle   msg="get the inet address"
     */
    public final static String UTIL_GUID_LOCALINETADDRESS = "UTIL_GUID_LOCALINETADDRESS";

    /**
     * @msg.bundle   msg="Could not get the local IP address using InetAddress.getLocalHost()!"
     */
    public final static String UTIL_GUID_UNKNOWNHOST = "UTIL_GUID_UNKNOWNHOST";

    /**
     * @msg.bundle   msg="getComponentInterface can only take type=remote|local - received type={0}"
     */
    public final static String INTERFACE_INVALID_TYPE = "INTERFACE_INVALID_TYPE";

    /**
     * @msg.bundle   msg="Error in template file. {0} must contain the interface parameter. Allowed values are remote
     *      (default) or local."
     */
    public final static String TAG_MISSING_INTERFACE_PARAMETER = "TAG_MISSING_INTERFACE_PARAMETER";

    /**
     * @msg.bundle   msg="The interface ''{0}'' not found!"
     */
    public final static String INTERFACE_NOT_FOUND = "INTERFACE_NOT_FOUND";

    /**
     * @msg.bundle   msg="The bean implementation class for interface ''{0}'' not found!"
     */
    public final static String INTERFACE_IMPL_NOT_FOUND = "INTERFACE_IMPL_NOT_FOUND";

    /**
     * @msg.bundle   msg="''pattern'' parameter does not have a '''{0'}'' in it. '''{0'}'' is replaced by EJB name of
     *      the class under processing."
     */
    public final static String PATTERN_HAS_NO_PLACEHOLDER = "PATTERN_HAS_NO_PLACEHOLDER";

    /**
     * @msg.bundle   msg="Could not load the bean implementation class for interface ''{0}''! Make sure it's available
     *      for ejbdoclet."
     */
    public final static String INTERFACE_IMPL_COULDNT_LOAD = "INTERFACE_IMPL_COULDNT_LOAD";

    /**
     * @msg.bundle   msg="The data-object class for interface ''{0}'' not known!"
     */
    public final static String INTERFACE_DATAOBJECT_NOT_KNOWN = "INTERFACE_DATAOBJECT_NOT_KNOWN";

    /**
     * @msg.bundle   msg="No such EJB defined: {0}"
     */
    public final static String NOT_DEFINED = "NOT_DEFINED";

    /**
     * @msg.bundle   msg="Class ''{0}'' should be defined abstract if you want the ''{1}'' sub-task to generate the
     *      subclass properly."
     */
    public final static String CLASS_NOT_ABSTRACT = "CLASS_NOT_ABSTRACT";

    /**
     * @msg.bundle   msg="{0} can only take type=remote|local - received type={1}"
     */
    public final static String METHOD_ONLY_TAKES_REMOTE_OR_LOCAL = "METHOD_ONLY_TAKES_REMOTE_OR_LOCAL";

    /**
     * @msg.bundle   msg="You asked the bean class for a NULL interface name"
     */
    public final static String ASK_FOR_BEAN_FROM_NULL_INTERFACE = "ASK_FOR_BEAN_FROM_NULL_INTERFACE";

    /**
     * @msg.bundle   msg="Data class not found"
     */
    public final static String DATACLASS_NOT_FOUND = "DATACLASS_NOT_FOUND";

    /**
     * @msg.bundle   msg="Generated ejbPostCreate for corresponding ejbCreate method."
     */
    public final static String GENERATED_EJBPOSTCREATE = "GENERATED_EJBPOSTCREATE";

    /**
     * @msg.bundle   msg="The Bean class is needed but not found in Xdoclet source path for interface {0}"
     */
    public final static String BEAN_CLASS_NOT_FOUND_FOR_INTERFACE = "BEAN_CLASS_NOT_FOUND_FOR_INTERFACE";

    /**
     * @msg.bundle   msg="The current method is not a create method: {0}"
     */
    public final static String CURRENT_METHOD_NOT_CREATE = "CURRENT_METHOD_NOT_CREATE";

    /**
     * @msg.bundle   msg="XDoclet classpath missing J2EE classes"
     */
    public final static String MISSING_J2EE_CLASSES = "MISSING_J2EE_CLASSES";
}
